# Home assistant Configuration
# Author: Dennis Bakhuis
# Date  : 30 October 2020
homeassistant:
  name: !secret homeassistantname
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: !secret unit_system
  time_zone: !secret time_zone
  auth_mfa_modules:
    - type: notify
      include:
        - everybody


panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: !secret configurator_url
  nodered:
    title: Node-Red
    icon: mdi:shuffle-variant
    url: !secret nodered_url


alarm_control_panel:
  - platform: manual
    name: !secret alarm_name
    arming_time: 20
    trigger_time: 300


default_config:


http:
  ip_ban_enabled: true
  login_attempts_threshold: 3
  use_x_forwarded_for: true
  trusted_proxies: !include trusted_proxies.yaml


recorder:
  purge_keep_days: 5


telegram_bot:
  - platform: polling
    api_key: !secret bottoken
    allowed_chat_ids:
      - !secret chatid_dennis
      - !secret chatid_kim


notify:
  - platform: telegram
    name: telegram_dennis
    chat_id: !secret chatid_dennis
  - platform: telegram
    name: telegram_kim
    chat_id: !secret chatid_kim
  - name: everybody
    platform: group
    services:
      - service: telegram_dennis
      - service: telegram_kim


group: !include groups.yaml


automation: !include automations.yaml


script: !include scripts.yaml


scene: !include scenes.yaml


sensor:
  - platform: dsmr
    port: /dev/ttyUSB0
    dsmr_version: 4
  - platform: buienradar
    monitored_conditions:
      - stationname
      - barometerfc
      - barometerfcname
      - conditioncode
      - condition
      - conditiondetailed
      - conditionexact
      - symbol
      - feeltemperature
      - humidity
      - temperature
      - groundtemperature
      - windspeed
      - windforce
      - winddirection
      - windazimuth
      - pressure
      - visibility
      - windgust
      - precipitation
      - irradiance
      - precipitation_forecast_average
      - precipitation_forecast_total
      - rainlast24hour
      - rainlasthour


# influxdb:
#   host: !secret influxdb_host
#   include:
#     entities:
#       - sensor.power_consumption
#       - sensor.power_consumption_low
#       - sensor.power_consumption_normal
#       - sensor.gas_consumption


utility_meter:
  energy_daily_power:
    source: sensor.power_consumption
    cycle: daily
  energy_daily_gas:
    source: sensor.gas_consumption
    cycle: daily
  energy_weekly_power:
    source: sensor.power_consumption
    cycle: weekly
  energy_weekly_gas:
    source: sensor.gas_consumption
    cycle: weekly
  energy_monthly_power:
    source: sensor.power_consumption
    cycle: monthly
  energy_monthly_gas:
    source: sensor.gas_consumption
    cycle: monthly


mqtt:
  broker: !secret mqttbroker


light:
  - platform: mqtt
    name: "Portiek"
    command_topic: !secret portiek_command
    payload_on: "on"
    payload_off: "off"
    state_topic: !secret portiek_state
  - platform: mqtt
    name: "Voordeur"
    command_topic: !secret voordeur_command
    payload_on: "on"
    payload_off: "off"
    state_topic: !secret voordeur_state
  - platform: mqtt
    name: "Hal"
    command_topic: !secret hal_command
    payload_on: "on"
    payload_off: "off"
    state_topic: !secret hal_state
  - platform: mqtt
    name: "Serre"
    command_topic: !secret serre_command
    payload_on: "on"
    payload_off: "off"
    state_topic: !secret serre_state


# homeconnect:
#   client_id: !secret homeconnectclientid
#   client_secret: !secret homeconnectclientsecret


input_select:
  kitchen_lower_dimlevel:
    name: Keuken laag dimstand
    options:
      - Uit
      - Alles
      - Drie
      - Twee
    initial: Uit
  kitchen_higher_dimlevel:
    name: Keuken hoog dimstand
    options:
      - Wit
      - Geel
    initial: Wit
  eettafel_dimlevel:
    name: Eettafel dimstand
    options:
      - Dimstand 1
      - Dimstand 2
      - Dimstand 3
    initial: Dimstand 1
input_boolean:
  automatic_light_kitchen:
    name: Automatisch licht keuken
    initial: on
    icon: 'mdi:lightbulb'
  automatic_light_hal:
    name: Automatisch licht hal
    initial: on
    icon: 'mdi:lightbulb'


wake_on_lan:


webostv:
  host: !secret webostv_ip
  name: LG Television
  turn_on_action:
    service: wake_on_lan.send_magic_packet
    data:
      mac: !secret webostv_mac
  customize:
    sources:
      - HDMI 3
      - Netflix
      - Prime Video

