# Home assistant Configuration
# Author: Dennis Bakhuis
# Date  : 2023-07-14
homeassistant:
  auth_mfa_modules:
    - type: notify
      include:
        - everybody


default_config:


alarm_control_panel:
  - platform: manual
    name: Bakhuis alarm
    arming_time: 30
    delay_time: 0
    trigger_time: 120
    disarmed:
      trigger_time: 0
    armed_home:
      arming_time: 0
      delay_time: 0


http:
  ip_ban_enabled: true
  login_attempts_threshold: 3
  use_x_forwarded_for: true
  trusted_proxies: !include trusted_proxies.yaml


recorder:
  purge_keep_days: 5


telegram_bot:
  - platform: polling
    api_key: !secret bottoken
    allowed_chat_ids:
      - !secret chatid_dennis
      - !secret chatid_kim


notify:
  - platform: telegram
    name: telegram_dennis
    chat_id: !secret chatid_dennis
  - platform: telegram
    name: telegram_kim
    chat_id: !secret chatid_kim
  - name: everybody
    platform: group
    services:
      - service: telegram_dennis
      - service: telegram_kim


group: !include groups.yaml


automation: !include automations.yaml


script: !include scripts.yaml


scene: !include scenes.yaml


sensor: !include_dir_merge_list sensors/


# Data collection
influxdb:
  api_version: 2
  ssl: false
  host: !secret influxdb_host
  port: !secret influxdb_port
  token: !secret influxdb_token
  organization: !secret influxdb_organization
  bucket: !secret influxdb_bucket
  include:
    entities:
      - sensor.energy_consumption_totals
      - sensor.gas_consumption
      - sensor.br_temperature
      - sensor.power_production


apache_kafka:
  ip_address: !secret kafka_broker_url
  port: !secret kafka_broker_port
  topic: !secret kafka_topic
  filter:
    include_entities:
      - sensor.power_production


# Custom UI
input_select:
  kitchen_lower_dimlevel:
    name: Keuken laag dimstand
    options:
      - Uit
      - Alles
      - Drie
      - Twee
    initial: Uit

  kitchen_higher_dimlevel:
    name: Keuken hoog dimstand
    options:
      - Wit
      - Geel
    initial: Wit

  eettafel_dimlevel:
    name: Eettafel dimstand
    options:
      - Dimstand 1
      - Dimstand 2
      - Dimstand 3
    initial: Dimstand 1


input_boolean:
  automatic_light_kitchen:
    name: Automatisch licht keuken
    initial: on
    icon: 'mdi:lightbulb'

  automatic_light_hal:
    name: Automatisch licht hal
    initial: on
    icon: 'mdi:lightbulb'

  alarm_silent_mode:
    name: Alarm stille modus
    initial: off
    icon: 'mdi:bullhorn'


wake_on_lan:
