# Home assistant Configuration
# Author: Dennis Bakhuis
# Date  : 2024-09-16
homeassistant:
  auth_mfa_modules:
    - type: notify
      include:
        - everybody


default_config:


http:
  ip_ban_enabled: true
  login_attempts_threshold: 3
  use_x_forwarded_for: true
  trusted_proxies: !include trusted_proxies.yaml


recorder:
  purge_keep_days: 5


telegram_bot:
  - platform: polling
    api_key: !secret bottoken
    allowed_chat_ids:
      - !secret chatid_dennis
      - !secret chatid_kim

notify:
  - platform: telegram
    name: telegram_dennis
    chat_id: !secret chatid_dennis
  - platform: telegram
    name: telegram_kim
    chat_id: !secret chatid_kim
  - name: everybody
    platform: group
    services:
      - service: telegram_dennis
      - service: telegram_kim


script: !include scripts.yaml
automation: !include automations.yaml
scene: !include scenes.yaml
mqtt: !include mqtt.yaml


# Data collection
influxdb:
  api_version: 2
  ssl: false
  host: !secret influxdb_host
  port: !secret influxdb_port
  token: !secret influxdb_token
  organization: !secret influxdb_organization
  bucket: !secret influxdb_bucket
  include:
    entities:
      - sensor.energy_consumption_totals
      - sensor.gas_consumption
      - sensor.br_temperature
      - sensor.power_production


wake_on_lan:
