- id: '1728061786367'
  name: Keuken wit
  entities:
    light.texas_instruments_cc2652_keuken_alles:
      min_color_temp_kelvin: 2000
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 500
      supported_color_modes:
      - color_temp
      color_mode: color_temp
      brightness: 254
      color_temp_kelvin: 5025
      color_temp: 199
      hs_color:
      - 27.028
      - 18.905
      rgb_color:
      - 255
      - 228
      - 206
      xy_color:
      - 0.371
      - 0.349
      off_with_transition: false
      off_brightness:
      friendly_name: Texas Instruments CC2652 Keuken alles
      supported_features: 40
      state: 'on'
  metadata:
    light.texas_instruments_cc2652_keuken_alles:
      entity_only: true
  icon: mdi:briefcase
- id: '1728062625347'
  name: Keuken geel
  entities:
    light.texas_instruments_cc2652_keuken_alles:
      min_color_temp_kelvin: 2000
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 500
      supported_color_modes:
      - color_temp
      color_mode: color_temp
      brightness: 254
      color_temp_kelvin: 2985
      color_temp: 335
      hs_color:
      - 27.85
      - 57.304
      rgb_color:
      - 255
      - 176
      - 108
      xy_color:
      - 0.498
      - 0.383
      off_with_transition: false
      off_brightness:
      friendly_name: Texas Instruments CC2652 Keuken alles
      supported_features: 40
      state: 'on'
  metadata:
    light.texas_instruments_cc2652_keuken_alles:
      entity_only: true
  icon: mdi:briefcase
- id: '1728062799017'
  name: Keuken fornuis
  entities:
    light.texas_instruments_cc2652_keuken_achter:
      min_color_temp_kelvin: 2000
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 500
      supported_color_modes:
      - color_temp
      color_mode:
      brightness:
      color_temp_kelvin:
      color_temp:
      hs_color:
      rgb_color:
      xy_color:
      off_with_transition: false
      off_brightness: 254
      friendly_name: Texas Instruments CC2652 Keuken achter
      supported_features: 40
      state: 'off'
    light.texas_instruments_cc2652_keuken_tuin:
      min_color_temp_kelvin: 2000
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 500
      supported_color_modes:
      - color_temp
      color_mode:
      brightness:
      color_temp_kelvin:
      color_temp:
      hs_color:
      rgb_color:
      xy_color:
      off_with_transition: false
      off_brightness: 254
      friendly_name: Texas Instruments CC2652 Keuken tuin
      supported_features: 40
      state: 'off'
    light.texas_instruments_cc2652_keuken_fornuis:
      min_color_temp_kelvin: 2000
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 500
      supported_color_modes:
      - color_temp
      color_mode: color_temp
      brightness: 92
      color_temp_kelvin: 2666
      color_temp: 375
      hs_color:
      - 28.47
      - 66.821
      rgb_color:
      - 255
      - 165
      - 84
      xy_color:
      - 0.53
      - 0.388
      off_with_transition: false
      off_brightness:
      friendly_name: Texas Instruments CC2652 Keuken fornuis
      supported_features: 40
      state: 'on'
  icon: mdi:movie-play
  metadata:
    light.texas_instruments_cc2652_keuken_achter:
      entity_only: true
    light.texas_instruments_cc2652_keuken_tuin:
      entity_only: true
    light.texas_instruments_cc2652_keuken_fornuis:
      entity_only: true
- id: '1728062936829'
  name: Keuken tuin
  entities:
    light.texas_instruments_cc2652_keuken_fornuis:
      min_color_temp_kelvin: 2000
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 500
      supported_color_modes:
      - color_temp
      color_mode:
      brightness:
      color_temp_kelvin:
      color_temp:
      hs_color:
      rgb_color:
      xy_color:
      off_with_transition: false
      off_brightness: 92
      friendly_name: Texas Instruments CC2652 Keuken fornuis
      supported_features: 40
      state: 'off'
    light.texas_instruments_cc2652_keuken_achter:
      min_color_temp_kelvin: 2000
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 500
      supported_color_modes:
      - color_temp
      color_mode:
      brightness:
      color_temp_kelvin:
      color_temp:
      hs_color:
      rgb_color:
      xy_color:
      off_with_transition: false
      off_brightness: 254
      friendly_name: Texas Instruments CC2652 Keuken achter
      supported_features: 40
      state: 'off'
    light.texas_instruments_cc2652_keuken_tuin:
      min_color_temp_kelvin: 2000
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 500
      supported_color_modes:
      - color_temp
      color_mode: color_temp
      brightness: 64
      color_temp_kelvin: 2710
      color_temp: 369
      hs_color:
      - 28.373
      - 65.405
      rgb_color:
      - 255
      - 167
      - 88
      xy_color:
      - 0.524
      - 0.388
      off_with_transition: false
      off_brightness:
      friendly_name: Texas Instruments CC2652 Keuken tuin
      supported_features: 40
      state: 'on'
  icon: mdi:movie-play
  metadata:
    light.texas_instruments_cc2652_keuken_achter:
      entity_only: true
    light.texas_instruments_cc2652_keuken_fornuis:
      entity_only: true
    light.texas_instruments_cc2652_keuken_tuin:
      entity_only: true
- id: '1728063041238'
  name: Keuken alles
  entities:
    light.texas_instruments_cc2652_keuken_alles:
      min_color_temp_kelvin: 2000
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 500
      supported_color_modes:
      - color_temp
      color_mode: color_temp
      brightness: 46
      color_temp_kelvin: 2202
      color_temp: 454
      hs_color:
      - 29.79
      - 84.553
      rgb_color:
      - 255
      - 146
      - 39
      xy_color:
      - 0.579
      - 0.388
      off_with_transition: false
      off_brightness:
      friendly_name: Texas Instruments CC2652 Keuken alles
      supported_features: 40
      state: 'on'
  icon: mdi:movie-play
  metadata:
    light.texas_instruments_cc2652_keuken_alles:
      entity_only: true
- id: '1728063086533'
  name: Keuken uit
  entities:
    light.texas_instruments_cc2652_keuken_alles:
      min_color_temp_kelvin: 2000
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 500
      supported_color_modes:
      - color_temp
      color_mode:
      brightness:
      color_temp_kelvin:
      color_temp:
      hs_color:
      rgb_color:
      xy_color:
      off_with_transition: false
      off_brightness: 92
      friendly_name: Texas Instruments CC2652 Keuken alles
      supported_features: 40
      state: 'off'
  icon: mdi:lightbulb-group-off
  metadata:
    light.texas_instruments_cc2652_keuken_alles:
      entity_only: true
