# Serre
listen_serre:
    alias: Spotify serre
    sequence:
        - service: media_player.turn_on
          entity_id: media_player.denon_avr_zone2
        - delay: 00:00:01
        - service: media_player.select_source
          entity_id: media_player.denon_avr_zone2
          data_template:
            source: HEOS Music
        - delay: 00:00:01
        - service: media_player.volume_set
          entity_id: media_player.denon_avr_zone2
          data_template:
            volume_level: 0.30

media_off_serre:
    alias: media uit serre
    sequence:
        - service: media_player.turn_off
          data:
            entity_id: media_player.denon_avr_zone2

# Woonkamer
listen_woonkamer:
    alias: Spotify woonkamer
    sequence:
        - service: media_player.turn_on
          entity_id: media_player.denon_avr
        - delay: 00:00:02
        - service: media_player.select_source
          entity_id: media_player.denon_avr
          data_template:
            source: HEOS Music
        - delay: 00:00:01
        - service: media_player.turn_off
          entity_id: media_player.lg_television
        - service: switch.turn_off
          entity_id: switch.plug_2_xbox
        - service: switch.turn_off
          entity_id: switch.plug_1_subwoover
        - delay: 00:00:01
        - service: media_player.volume_set
          entity_id: media_player.denon_avr
          data_template:
            volume_level: 0.30

watch_cast:
    alias: Cast kijken
    sequence:
        - service: media_player.turn_on
          entity_id: media_player.denon_avr
        - service: media_player.turn_on
          entity_id: media_player.lg_television
        - delay: 00:00:02
        - service: media_player.select_source
          entity_id: media_player.denon_avr
          data_template:
            source: Chromecast
        - service: media_player.select_source
          entity_id: media_player.lg_television
          data_template:
            source: HDMI 3
        - service: switch.turn_off
          entity_id: switch.plug_2_xbox
        - service: switch.turn_on
          entity_id: switch.plug_1_subwoover
        - delay: 00:00:02
        - service: media_player.volume_set
          entity_id: media_player.denon_avr
          data_template:
            volume_level: 0.50

play_xbox:
    alias: Gamen
    sequence:
        - service: media_player.turn_on
          entity_id: media_player.denon_avr
        - service: media_player.turn_on
          entity_id: media_player.lg_television
        - delay: 00:00:02
        - service: media_player.select_source
          entity_id: media_player.denon_avr
          data_template:
            source: Xbox
        - service: media_player.select_source
          entity_id: media_player.lg_television
          data_template:
            source: HDMI 3
        - delay: 00:00:01
        - service: media_player.volume_set
          entity_id: media_player.denon_avr
          data_template:
            volume_level: 0.46
        - service: switch.turn_on
          entity_id: switch.plug_1_subwoover

media_off:
    alias: Alle media uit
    sequence:
        - service: media_player.turn_off
          entity_id: media_player.denon_avr
        - service: media_player.turn_off
          entity_id: media_player.lg_television
        - service: switch.turn_off
          entity_id: switch.plug_2_xbox
        - service: switch.turn_off
          entity_id: switch.plug_1_subwoover

###################
# Security system #
###################

sound_alarm:
  alias: Sound alarm for two minutes
  sequence:
      - service: switch.turn_on
        data:
          entity_id: switch.neo_coolcam_siren_alarm_switch
      #- service: media_player.turn_on
        #data:
          #entity_id: media_player.yamaha_receiver_living_room
      #- service: shell_command.volumio_clearqueue
      #- service: shell_command.volumio_playlist_alarm
      #- service: media_player.select_source
        #data:
          #entity_id: media_player.yamaha_receiver_living_room
          #source: AV1
      #- service: media_player.volume_set
        #data:
          #entity_id: media_player.yamaha_receiver_living_room
          #volume_level: 0.80
      - delay:
          seconds: 5
      - service: switch.turn_off
        data:
          entity_id: switch.neo_coolcam_siren_alarm_switch
      #- service: shell_command.volumio_stop
      #- service: media_player.turn_off
        #data:
          #entity_id: media_player.yamaha_receiver_living_room

warning_flash:
  alias: Flash lights
  sequence:
  - service: switch.turn_on
    data:
      entity_id: switch.fibaro_system_fgs223_double_relay_switch
  - service: switch.turn_on
    data:
      entity_id: switch.fibaro_system_fgs223_double_relay_switch_2
  - service: light.turn_on
    data:
      entity_id: light.fibaro_system_fgd212_dimmer_2_level_2
  - delay:
      seconds: 1
  - service: switch.turn_off
    data:
      entity_id: switch.fibaro_system_fgs223_double_relay_switch
  - service: switch.turn_off
    data:
      entity_id: switch.fibaro_system_fgs223_double_relay_switch_2
  - service: light.turn_off
    data:
      entity_id: light.fibaro_system_fgd212_dimmer_2_level_2
  - delay:
      seconds: 1

warning_flash_repeat:
    # flash porch/portiek/kitchen light three times ~12 seconds
    alias: flash three times
    sequence:
    - service: script.turn_on
      data:
        entity_id: script.warning_flash
    - delay:
        seconds: 0.1
    - wait_template: "{{is_state('script.warning_flash', 'off')}}"
    - service: script.turn_on
      data:
        entity_id: script.warning_flash
    - delay:
        seconds: 0.1
    - wait_template: "{{is_state('script.warning_flash', 'off')}}"
    - service: script.turn_on
      data:
        entity_id: script.warning_flash
    - delay:
        seconds: 0.1
    - wait_template: "{{is_state('script.warning_flash', 'off')}}"

alarm_tripped_delayed:
    # Takes approximately 40 seconds
    alias: Alarm tripped delayed
    sequence:
    - service: script.turn_on
      data:
        entity_id: script.warning_flash_repeat
    - delay:
        seconds: 2
    - wait_template: "{{is_state('script.warning_flash_repeat', 'off')}}"
    - service: switch.turn_on
      data:
        entity_id: switch.fibaro_system_fgs223_double_relay_switch
    - service: switch.turn_on
      data:
        entity_id: switch.fibaro_system_fgs223_double_relay_switch_2
    - service: light.turn_on
      data:
        entity_id: light.fibaro_system_fgd212_dimmer_2_level_2
    - delay:
        seconds: 20
    - service: script.turn_on
      data:
        entity_id: script.sound_alarm

alarm_tripped:
    # Starts immediately
    alias: Alarm tripped
    sequence:
    - service: switch.turn_on
      data:
        entity_id: switch.fibaro_system_fgs223_double_relay_switch
    - service: switch.turn_on
      data:
        entity_id: switch.fibaro_system_fgs223_double_relay_switch_2
    - service: light.turn_on
      data:
        entity_id: light.fibaro_system_fgd212_dimmer_2_level_2
    - service: script.turn_on
      data:
        entity_id: script.sound_alarm

receiver_mute_toggle:
  sequence:
    - service: media_player.volume_mute
      data_template:
        entity_id: media_player.denon_avr
        is_volume_muted: >-
          {%- if states.media_player.denon_avr.attributes.is_volume_muted == false -%}
          true
          {%- else -%}
          false
          {%- endif -%}

volume_up:
  sequence:
    service: media_player.volume_set
    entity_id: media_player.denon_avr
    data_template:
      volume_level: '{{ states.media_player.denon_avr.attributes.volume_level + 0.02 }}'

volume_down:
  sequence:
    service: media_player.volume_set
    entity_id: media_player.denon_avr
    data_template:
      volume_level: '{{ states.media_player.denon_avr.attributes.volume_level - 0.02 }}'

receiver_mute_toggle_zone2:
  sequence:
    - service: media_player.volume_mute
      data_template:
        entity_id: media_player.denon_avr_zone2
        is_volume_muted: >-
          {%- if states.media_player.denon_avr_zone2.attributes.is_volume_muted == false -%}
          true
          {%- else -%}
          false
          {%- endif -%}

volume_up_zone2:
  sequence:
    service: media_player.volume_set
    entity_id: media_player.denon_avr_zone2
    data_template:
      volume_level: '{{ states.media_player.denon_avr_zone2.attributes.volume_level + 0.02 }}'

volume_down_zone2:
  sequence:
    service: media_player.volume_set
    entity_id: media_player.denon_avr_zone2
    data_template:
      volume_level: '{{ states.media_player.denon_avr_zone2.attributes.volume_level - 0.02 }}'

