listen_serre:
  alias: Spotify serre
  sequence:
  - service: media_player.turn_on
    entity_id: media_player.home_theater_2
  - delay: 00:00:05
  - service: media_player.select_source
    entity_id: media_player.home_theater_2
    data_template:
      source: HEOS Music
  - delay: 00:00:02
  - service: media_player.volume_set
    entity_id: media_player.home_theater_2
    data_template:
      volume_level: 0.3
media_off_serre:
  alias: media uit serre
  sequence:
  - service: media_player.turn_off
    data:
      entity_id: media_player.home_theater_2
listen_woonkamer:
  alias: Spotify woonkamer
  sequence:
  - service: media_player.turn_on
    entity_id: media_player.home_theater
  - delay: 00:00:05
  - service: media_player.select_source
    entity_id: media_player.home_theater
    data_template:
      source: HEOS Music
  - delay: 00:00:02
  - service: media_player.turn_off
    entity_id: media_player.lg_television
  - service: media_player.turn_off
    entity_id: media_player.apple_tv
  - service: switch.turn_off
    entity_id: switch.plug_2_xbox
  - service: switch.turn_off
    entity_id: switch.plug_1_subwoover
  - service: media_player.volume_set
    entity_id: media_player.home_theater
    data_template:
      volume_level: 0.3
watch_cast:
  alias: Apple TV kijken
  sequence:
  - service: media_player.turn_on
    data: {}
    target:
      entity_id:
      - media_player.home_theater
      - media_player.lg_television
  - delay: 00:00:03
  - service: media_player.select_source
    data:
      source: HDMI 2
    target:
      entity_id: media_player.lg_television
  - service: media_player.select_source
    data:
      source: Cast
    target:
      entity_id: media_player.home_theater
  - service: switch.turn_on
    entity_id: switch.plug_1_subwoover
  - delay:
      hours: 0
      minutes: 0
      seconds: 3
      milliseconds: 0
  - service: media_player.volume_set
    data:
      volume_level: 0.55
    target:
      entity_id: media_player.home_theater
  - service: switch.turn_off
    entity_id: switch.plug_2_xbox
  - service: script.turn_on_apple_tv
    data: {}
  icon: mdi:apple
  mode: single
play_xbox:
  alias: Gamen
  sequence:
  - service: media_player.turn_on
    entity_id: media_player.home_theater
  - service: media_player.turn_on
    entity_id: media_player.lg_television
  - delay: 00:00:04
  - service: media_player.select_source
    entity_id: media_player.home_theater
    data_template:
      source: Xbox
  - service: media_player.select_source
    entity_id: media_player.lg_television
    data_template:
      source: HDMI 2
  - delay: 00:00:02
  - service: media_player.volume_set
    entity_id: media_player.home_theater
    data_template:
      volume_level: 0.45
  - service: switch.turn_on
    entity_id: switch.plug_1_subwoover
  - service: switch.turn_off
    entity_id: switch.plug_2_xbox
media_off:
  alias: Alle media uit
  sequence:
  - service: media_player.turn_off
    data: {}
    target:
      entity_id:
      - media_player.home_theater
      - media_player.apple_tv
      - media_player.lg_television
  - service: switch.turn_off
    data: {}
    target:
      entity_id:
      - switch.plug_2_xbox
      - switch.plug_1_subwoover
turn_on_apple_tv:
  alias: Living Room Apple TV On
  sequence:
  - if:
    - '{{is_state(''media_player.apple_tv'', ''standby'' )}}'
    then:
    - service: remote.send_command
      target:
        entity_id: remote.apple_tv
      data:
        delay_secs: 1
        command:
        - home
  mode: single
  icon: mdi:apple
