- trigger:
    - platform: time_pattern
      id: "update_state"
      minutes: "/15"
    - platform: time_pattern
      id: "reset_sensor"
      hours: "23"
      minutes: "59"
  sensor:
    - name: Degree Days
      unique_id: degree_days
      state: >-
        {% if trigger.id == "update_state" %}
          {% set timestep = 0.25 %}
          {% set base = 18 %}
          {% set current_temp = states('sensor.panasonic_heat_pump_main_outside_temp')|float(0) or states('sensor.br_temperature')|float(0) %}
          {% set partial_dd = max(0, (base - current_temp) / (24 / timestep)) %}
          {{ this.state | float() + partial_dd }}
        {% else %}
          {{ 0 }}
        {% endif %}
      state_class: total_increasing
