# - platform: buienradar
#   monitored_conditions:
#     - stationname
#     - barometerfc
#     - barometerfcname
#     - conditioncode
#     - condition
#     - conditiondetailed
#     - conditionexact
#     - symbol
#     - feeltemperature
#     - humidity
#     - temperature
#     - groundtemperature
#     - windspeed
#     - windforce
#     - winddirection
#     - windazimuth
#     - pressure
#     - visibility
#     - windgust
#     - precipitation
#     - irradiance
#     - precipitation_forecast_average
#     - precipitation_forecast_total
#     - rainlast24hour
#     - rainlasthour
