- platform: template
  sensors:
    solar_angle:
      friendly_name: "Sun angle"
      unit_of_measurement: 'degrees'
      value_template: "{{ state_attr('sun.sun', 'elevation') }}"
    energy_consumption_totals:
      friendly_name: "Total energy consumption"
      unit_of_measurement: 'KWh'
      value_template: "{{ states.sensor.energy_consumption_tarif_1.state | float + states.sensor.energy_consumption_tarif_2.state | float }}"
